name: 'dap'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'domain_dbt'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
#test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["../../dags/domain_utils/macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
    dap:
        enabled: true
        materialized: table
    my_transfer_project_refactor:
        reports:
            +enabled: "{{ target.name == 'preprod' }}"

# Define environment-specific variables
vars:
    # preprod configuration
    preprod_config:
        m_reports:
            DBT_SRC_GCP_PROJECT: "sb-stul-20241030-175302"
            DBT_SRC_GCP_DATASET: "coreruby"
            DBT_GCP_DATASET: "transfer_project_preprod"

        default:
            DBT_SRC_GCP_PROJECT: "sb-stul-20241030-175302"
            DBT_SRC_GCP_DATASET: "coreruby"
            DBT_GCP_DATASET: "transfer_project_preprod"
            DBT_SRC_TABLE_NAME: "coreruby_transactions_native"
            DBT_TGT_TABLE_NAME: "coreruby_transactions_native_raw"

    # Production configuration
    prod_config:
        m_reports:
            DBT_SRC_GCP_PROJECT: "sb-stul-20241030-175302"
            DBT_SRC_GCP_DATASET: "coreruby"
            DBT_GCP_DATASET: "transfer_project_preprod"

        default:
            DBT_SRC_GCP_PROJECT: "sb-stul-20241030-175302"
            DBT_SRC_GCP_DATASET: "coreruby"
            DBT_GCP_DATASET: "transfer_project_preprod"
            DBT_SRC_TABLE_NAME: "coreruby_transactions_native"
            DBT_TGT_TABLE_NAME: "coreruby_transactions_native_raw_prod"