mo_report:
  DBT_SRC_GCP_PROJECT: my-proprod-project
  DBT_SRC_GCP_DATASET: event
  DBT_GCP_DATASET: my_operational
  DBT_SRC_TABLE_NAME: coreruby_transactions_native
  DBT_TGT_TABLE_NAME: reconciliation_mo_report
  MODELS: mo_report
m1_report:
  DBT_SRC_GCP_PROJECT: my-proprod-project
  DBT_SRC_GCP_DATASET: event
  DBT_GCP_DATASET: my_operational
  DBT_SRC_TABLE_NAME: coreruby_transactions_native
  DBT_TGT_TABLE_NAME: reconciliation_m1_report
  MODELS: m1_report

