mo_report:
  DBT_SRC_GCP_PROJECT: "sb-stul-20241030-175302"
  DBT_SRC_GCP_DATASET: "coreruby"
  DBT_GCP_DATASET: "transfer_project_preprod"
  DBT_SRC_TABLE_NAME: "transfer_project_preprod"
  DBT_TGT_TABLE_NAME: "coreruby_transactions_native"
  MODELS: mo_report
m1_report:
  DBT_SRC_GCP_PROJECT: "sb-stul-20241030-175302"
  DBT_SRC_GCP_DATASET: "coreruby"
  DBT_GCP_DATASET: "transfer_project_preprod"
  DBT_SRC_TABLE_NAME: "transfer_project_preprod"
  DBT_TGT_TABLE_NAME: "coreruby_transactions_native"
  MODELS: m1_report
default:
  DBT_SRC_GCP_PROJECT: "sb-stul-20241030-175302"
  DBT_SRC_GCP_DATASET: "coreruby"
  DBT_GCP_DATASET: "transfer_project_preprod"
  DBT_SRC_TABLE_NAME: "coreruby_transactions_native"
  DBT_TGT_TABLE_NAME: "coreruby_transactions_native_raw"
  MODELS: default
